apiVersion: v1
kind: Secret
metadata:
  name: livekit-blobstorage-secret
type: Opaque
stringData:
  AZURE_CONTAINER_NAME: "recordings"
  AZURE_STORAGE_ACCOUNT: "tfstateaccountn12g4v"
  AZURE_STORAGE_KEY: "core-infra-prod.tfstate"
